import logging

from odoo import SUPERUSER_ID, api

_logger = logging.getLogger(__name__)


def migrate(cr, version):
    reset_templates(cr)


def reset_templates(cr):
    """Reset templates with source files to update their translations

    Currently, the migration of the database does not update the values or translations of the templates
    generated by code, so they had to be deleted or reloaded to be regenerated. But that did not update the
    translations so they also had to be reloaded by forcing the overwriting of existing terms.

    Odoo has already a method to perform both actions which is to reset the template.
    This way it is only necessary to select all the templates generated by code and use the method to solve
    both problems.
    """
    env = api.Environment(cr, SUPERUSER_ID, {})
    templates = env["mail.template"].search([("template_fs", "!=", False)])
    templates.reset_template()
    _logger.info("%s templates with source files were reset successfully.", len(templates))
